name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger action when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file

    - name: Run the application
      run: |
        python application.py  # Command to run your application.py

    - name: Deploy your application (example)
      run: |
        echo "Deploying application..."
        # Your deploy steps here (e.g., copying files to server, or other deployment commands)
